#!/bin/sh

#########################################
# Convenience file to run the packaged
# directory executable for validating
# deployment.
#########################################

# Fail immediately
set -e

# Version
OFFICE_DEMO_VERSION=0.1.0

# Change to release directory package
cd target/officetool_demo-${OFFICE_DEMO_VERSION}/officetool_demo-${OFFICE_DEMO_VERSION}/bin

# Delegate to the bin executable
./officedemo $@