#!/bin/sh

#########################################
# Convenience file to run the packaged
# directory executable for validating
# deployment.
#########################################

# Version
OFFICE_BUILDING_VERSION=0.0.2

# Change to release directory package
cd target/officebuilding-${OFFICE_BUILDING_VERSION}-release/officebuilding-${OFFICE_BUILDING_VERSION}/bin

# Delegate to the bin executable
./officebuilding $@