#!/bin/sh

#########################################
# Convenience file to run the packaged
# directory executable for validating
# deployment.
#########################################

# Fail immediately
set -e

# Change to release directory package ('*' to match current version as should only be one version being built)
cd target/OfficeFloor-*-release/OfficeFloor-*/bin

# Delegate to the bin executable
. ./officebuilding $@
