AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: DESCRIPTION

Globals:
  Function:
    Timeout: 20
  Api:
    BinaryMediaTypes: 
    - "*/*"

Resources:
  ARTIFACT_ID:
    Type: AWS::Serverless::Function
    Properties:
      Handler: net.officefloor.server.aws.sam.OfficeFloorSam::handleRequest
      Runtime: java11
      MemorySize: 256
      Policies: AmazonDynamoDBFullAccess
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        Request:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            