CREATE TABLE REFERENCE_DATA ( ID VARCHAR(5) PRIMARY KEY, MESSAGE VARCHAR(20) );

INSERT INTO REFERENCE_DATA ( ID, MESSAGE ) VALUES ( '1', 'World' );
INSERT INTO REFERENCE_DATA ( ID, MESSAGE ) VALUES ( '2', 'there' );
