CREATE TABLE ACCOUNT
( ACCOUNT_ID    INTEGER
, ACCOUNT_NAME  VARCHAR(20) NOT NULL
);
ALTER TABLE ACCOUNT ADD PRIMARY KEY ( ACCOUNT_ID );
CREATE INDEX IDX_ACCOUNT_NAME ON ACCOUNT ( ACCOUNT_NAME );

CREATE TABLE PRODUCT
( PRODUCT_ID    INTEGER
, PRODUCT_NAME  VARCHAR(20) NOT NULL
);
ALTER TABLE PRODUCT ADD PRIMARY KEY ( PRODUCT_ID );
CREATE INDEX IDX_PRODUCT_NAME ON PRODUCT ( PRODUCT_NAME );

CREATE TABLE PURCHASE
( PURCHASE_ID   INTEGER
, ACCOUNT_ID    INTEGER NOT NULL
, PRODUCT_ID    INTEGER NOT NULL
);
ALTER TABLE PURCHASE ADD PRIMARY KEY ( PURCHASE_ID );
ALTER TABLE PURCHASE ADD FOREIGN KEY ( ACCOUNT_ID ) REFERENCES ACCOUNT ( ACCOUNT_ID );
ALTER TABLE PURCHASE ADD FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT ( PRODUCT_ID );
ALTER TABLE PURCHASE ADD UNIQUE ( ACCOUNT_ID, PRODUCT_ID );

CREATE TABLE PURCHASE_PRICE
( PURCHASE_PRICE_ID INTEGER
, ACCOUNT_ID        INTEGER NOT NULL
, PRODUCT_ID        INTEGER NOT NULL
, PRICE             REAL NOT NULL
, COMMENTS          VARCHAR(30) NULL
);
ALTER TABLE PURCHASE_PRICE ADD PRIMARY KEY ( PURCHASE_PRICE_ID );
ALTER TABLE PURCHASE_PRICE ADD FOREIGN KEY ( ACCOUNT_ID, PRODUCT_ID ) REFERENCES PURCHASE ( ACCOUNT_ID, PRODUCT_ID );