CREATE TABLE REFERENCE_DATA ( KEY VARCHAR(5) PRIMARY KEY, MESSAGE VARCHAR(20) );

INSERT INTO REFERENCE_DATA ( KEY, MESSAGE ) VALUES ( '1', 'World' );
INSERT INTO REFERENCE_DATA ( KEY, MESSAGE ) VALUES ( '2', 'there' );
