package net.officefloor.tutorial.dynamodbhttpserver;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import net.officefloor.web.HttpObject;

/**
 * Post.
 * 
 * @author Daniel Sagenschneider
 */
// START SNIPPET: tutorial
@DynamoDBTable(tableName = "Post")
@HttpObject
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Post {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	private String message;
}
// END SNIPPET: tutorial