#!/bin/sh

#########################################
# Convenience file to run the packaged
# directory executable for validating
# deployment.
#########################################

# Fail immediately
set -e

# Change to release directory package ('*' to handle version)
cd target/officetool_demo-*/officetool_demo-*/bin

# Delegate to the bin executable
./officedemo $@