CREATE TABLE ACCOUNT
( ACCOUNT_ID    INTEGER
, ACCOUNT_NAME  VARCHAR(20) NOT NULL
);
ALTER TABLE ACCOUNT ADD PRIMARY KEY ( ACCOUNT_ID );
CREATE INDEX ACCOUNT_IDX_ACCOUNT_NAME ON ACCOUNT ( ACCOUNT_NAME );

CREATE TABLE PRODUCT
( PRODUCT_ID    INTEGER
, PRODUCT_NAME  VARCHAR(20) NOT NULL
);
ALTER TABLE PRODUCT ADD PRIMARY KEY ( PRODUCT_ID );
CREATE INDEX PRODUCT_IDX_PRODUCT_NAME ON PRODUCT ( PRODUCT_NAME );

CREATE TABLE PRODUCT_PRICE
( PRODUCT_ID    INTEGER
, QUANTITY      INTEGER
, PRICE         REAL NOT NULL
);
ALTER TABLE PRODUCT_PRICE ADD PRIMARY KEY ( PRODUCT_ID, QUANTITY );
ALTER TABLE PRODUCT_PRICE ADD FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT ( PRODUCT_ID );

CREATE TABLE PURCHASE_ORDER
( PURCHASE_ORDER_ID     INTEGER
, ACCOUNT_ID            INTEGER NOT NULL
);
ALTER TABLE PURCHASE_ORDER ADD PRIMARY KEY ( PURCHASE_ORDER_ID );
ALTER TABLE PURCHASE_ORDER ADD FOREIGN KEY ( ACCOUNT_ID ) REFERENCES ACCOUNT ( ACCOUNT_ID );

CREATE TABLE PURCHASE_ORDER_LINE_ITEM
( PURCHASE_ORDER_ID     INTEGER
, LINE_NUMBER           INTEGER
, PRODUCT_ID            INTEGER NOT NULL
, QUANTITY              INTEGER NOT NULL
, PRICE_ADJUSTMENT      REAL
, COMMENTS              VARCHAR(250)
);
ALTER TABLE PURCHASE_ORDER_LINE_ITEM ADD PRIMARY KEY ( PURCHASE_ORDER_ID, LINE_NUMBER );
ALTER TABLE PURCHASE_ORDER_LINE_ITEM ADD FOREIGN KEY ( PURCHASE_ORDER_ID ) REFERENCES PURCHASE_ORDER ( PURCHASE_ORDER_ID );
ALTER TABLE PURCHASE_ORDER_LINE_ITEM ADD FOREIGN KEY ( PRODUCT_ID, QUANTITY ) REFERENCES PRODUCT_PRICE ( PRODUCT_ID, QUANTITY );
