managed-object:
  source: net.officefloor.cache.constant.ConstantCacheManagedObjectSource
  qualifier: net.officefloor.tutorial.constantcachehttpserver.World
  properties:
    qualifier: net.officefloor.tutorial.constantcachehttpserver.World
    poll.interval: "300000"
