name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_JAVA_VERSION: 11
  LATEST_JAVA_VERSION: 15
  OFFICEFLOOR_CONTINUOUS_INTEGRATION: true
  OFFICEFLOOR_SKIP_VERSION_CHECK: true
  OFFICEFLOOR_CODE_COVERAGE: false
  OFFICEFLOOR_DOCKER_AVAILABLE: false
  OFFICEFLOOR_AWS_AVAILABLE: false
  OFFICEFLOOR_GCLOUD_AVAILABLE: true
  OFFICEFLOOR_SKIP_FAILED_COSMOS_TESTS: true

jobs:
  supported-java:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK ${{ env.BUILD_JAVA_VERSION }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ env.BUILD_JAVA_VERSION }}

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          !~/.m2/respository/net/officefloor
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}
        restore-keys: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}
        
    - name: Full test on linux
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        echo "OFFICEFLOOR_SKIP_VERSION_CHECK=false" >> $GITHUB_ENV
        echo "OFFICEFLOOR_DOCKER_AVAILABLE=true" >> $GITHUB_ENV
        echo "OFFICEFLOOR_AWS_AVAILABLE=true" >> $GITHUB_ENV
        echo "OFFICEFLOOR_CODE_COVERAGE=true" >> $GITHUB_ENV
        
    - name: Continuous Integration
      run: |
        echo "PATH $PATH"
        echo "JAVA_HOME $JAVA_HOME"
        echo "OFFICEFLOOR_SKIP_VERSION_CHECK $OFFICEFLOOR_SKIP_VERSION_CHECK"
        echo "OFFICEFLOOR_CODE_COVERAGE $OFFICEFLOOR_CODE_COVERAGE"
        echo "OFFICEFLOOR_DOCKER_AVAILABLE $OFFICEFLOOR_DOCKER_AVAILABLE"
        echo "OFFICEFLOOR_AWS_AVAILABLE $OFFICEFLOOR_AWS_AVAILABLE"
        echo "OFFICEFLOOR_GCLOUD_AVAILABLE $OFFICEFLOOR_GCLOUD_AVAILABLE"
        echo "OFFICEFLOOR_SKIP_FAILED_COSMOS_TESTS $OFFICEFLOOR_SKIP_FAILED_COSMOS_TESTS"
        mvn -V -B -e -DskipStress clean install --file officefloor/bom/pom.xml

    - name: Upload code coverage
      if: startsWith(matrix.os, 'ubuntu')
      run: bash <(curl -s https://codecov.io/bash)


  latest-java:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK ${{ env.LATEST_JAVA_VERSION }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ env.LATEST_JAVA_VERSION }}

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          !~/.m2/respository/net/officefloor
        key: ubuntu-latest-maven-${{ secrets.CACHE_VERSION }}
        restore-keys: ubuntu-latest-maven-${{ secrets.CACHE_VERSION }}
    
    - name: Full test except that GCP only supports Java 11
      run: |
        echo "OFFICEFLOOR_DOCKER_AVAILABLE=true" >> $GITHUB_ENV
        echo "OFFICEFLOOR_AWS_AVAILABLE=true" >> $GITHUB_ENV
        echo "OFFICEFLOOR_GCLOUD_AVAILABLE=false" >> $GITHUB_ENV

    - name: Continuous Integration
      run: |
        echo "PATH $PATH"
        echo "JAVA_HOME $JAVA_HOME"
        echo "OFFICEFLOOR_SKIP_VERSION_CHECK $OFFICEFLOOR_SKIP_VERSION_CHECK"
        echo "OFFICEFLOOR_CODE_COVERAGE $OFFICEFLOOR_CODE_COVERAGE"
        echo "OFFICEFLOOR_DOCKER_AVAILABLE $OFFICEFLOOR_DOCKER_AVAILABLE"
        echo "OFFICEFLOOR_AWS_AVAILABLE $OFFICEFLOOR_AWS_AVAILABLE"
        echo "OFFICEFLOOR_GCLOUD_AVAILABLE $OFFICEFLOOR_GCLOUD_AVAILABLE"
        echo "OFFICEFLOOR_SKIP_FAILED_COSMOS_TESTS $OFFICEFLOOR_SKIP_FAILED_COSMOS_TESTS"
        mvn -V -B -e -DskipStress clean install --file officefloor/bom/pom.xml
