version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AwsSamHttpServer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bkksf86gw8gu"
s3_prefix = "AwsSamHttpServer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
